title: style revolution plates
description: >- #
baseurl: "/srplates" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
theme: minima
permalink: pretty

exclude: [Gemfile*, node_modules, vendor]

collections:
  iiif:
    output: true
  plates:
    output: true
    source: plates.csv
    key: plate
    directory: plates
    layout: plate-page

defaults:
  - scope:
      path: ""
      type: iiif_collection
    values:
      layout: iiif_image

webrick:
  headers:
    "Access-Control-Allow-Origin": "*"
